/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.45
 * Generated at: 2018-01-08 11:42:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import cn.com.clm.utils.*;

public final class makeOrder_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("cn.com.clm.utils");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width,initial-scale=0.25\"/>\r\n");
      out.write("    <title>生成订单</title>\r\n");
      out.write("    <!-- Bootstrap -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/fore/css/bootstrap.min.css\">\r\n");
      out.write("    <!-- Font Awesome -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/fore/css/font-awesome.min.css\">\r\n");
      out.write("    <!-- Custom CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/fore/css/owl.carousel.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/fore/style.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/fore/css/responsive.css\">\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath() );
      out.write("/fore/js/jquery-1.8.2.min.js\"></script>  \r\n");
      out.write("    <script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath() );
      out.write("/fore/date/jquery.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath() );
      out.write("/fore/date/dateRange.js\"></script>\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath() );
      out.write("/fore/date/dateRange.css\"/>\r\n");
      out.write("    <style type=\"text/css\">\r\n");
      out.write("    \ttd,select{\r\n");
      out.write("    \t\tfont-family: 楷体;\r\n");
      out.write("    \t\tfont-size: 1.3em;\r\n");
      out.write("    \t\tfont-weight: 900;\r\n");
      out.write("    \t\tcolor:blue;\r\n");
      out.write("    \t}\r\n");
      out.write("    \t#startDate,#endDate{\r\n");
      out.write("    \t\tborder-radius:5px;\r\n");
      out.write("    \t}\r\n");
      out.write("    </style>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("   \r\n");
      out.write("    <div class=\"header-area\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-8\">\r\n");
      out.write("                    <div class=\"col-md-8\">\r\n");
      out.write("                    <div class=\"user-menu\">\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li>当前用户：</li>\r\n");
      out.write("                        \t<li><a href=\"#\"><i class=\"fa fa-user\"></i>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.u_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</a></li>\r\n");
      out.write("                            <li><a href=\"javascript:exitFun()\"><i class=\"fa fa-user\"></i> 退出</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <script type=\"text/javascript\">\r\n");
      out.write("                \tfunction exitFun(){\r\n");
      out.write("                \t\tvar b = confirm(\"你确定退出？\");\r\n");
      out.write("                \t\tif(b){\r\n");
      out.write("                \t\t\twindow.location.href='");
      out.print(request.getContextPath() );
      out.write("/fore/exit.jsp';\r\n");
      out.write("                \t\t}else{\r\n");
      out.write("                \t\t\t\r\n");
      out.write("                \t\t}\r\n");
      out.write("                \t}\r\n");
      out.write("                </script>\r\n");
      out.write("                </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div> <!-- End header area -->\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"site-branding-area\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-sm-6\">\r\n");
      out.write("                    <div class=\"logo\">\r\n");
      out.write("                        <h1><a href=\"#\">\r\n");
      out.write("                        \t<img id=\"myLogoImg\" style=\"height: 140px;width: 170px;position: absolute;top: 0px;left:930px;\">\r\n");
      out.write("                        \t</a>\r\n");
      out.write("\t\t\t\t\t\t</h1>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div> \r\n");
      out.write("\r\n");
      out.write("<script src='");
      out.print(request.getContextPath() );
      out.write("/fore/js/jquery-1.7.2.min.js'></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$.post(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/car/getLogoImg\",function(data){\r\n");
      out.write("\t $(\"#myLogoImg\").attr(\"src\",\"/car_img/\"+data);\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"mainmenu-area\" style=\"position: absolute;top: 80px;left:110px;margin: 0;\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"navbar-collapse collapse\" >\r\n");
      out.write("                    <ul class=\"nav navbar-nav\" style=\"border: 1px solid #ccc;border-radius:15px;\">\r\n");
      out.write("                        <li><a style=\"font-family: 仿宋;color:black;font-size: 2em;\" href=\"");
      out.print(request.getContextPath());
      out.write("/car/index/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.u_card}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">首页</a></li>\r\n");
      out.write("                        <li><a style=\"font-family: 仿宋;color:black;font-size: 2em;\" href=\"");
      out.print(request.getContextPath());
      out.write("/user/getUser/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.u_card}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">我的主页</a></li>\r\n");
      out.write("                        <li><a style=\"font-family: 仿宋;color:black;font-size: 2em;\" href=\"");
      out.print(request.getContextPath());
      out.write("/car/getPageCar?u_card=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.u_card}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">汽车查询</a></li>\r\n");
      out.write("                        <li class=\"active\"><a style=\"font-family: 仿宋;color:red;font-size: 2em;\" href=\"#\">生成订单</a></li>\r\n");
      out.write("                        <li><a style=\"font-family: 仿宋;color:black;font-size: 2em;\" href=\"");
      out.print(request.getContextPath());
      out.write("/order/getOrders?u_card=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.u_card}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">我的订单</a></li>\r\n");
      out.write("                        <li><a style=\"font-family: 仿宋;color:black;font-size: 2em;\" href=\"");
      out.print(request.getContextPath());
      out.write("/user/talk\">联系客服</a></li>\r\n");
      out.write("                    \t<li><a style=\"font-family: 仿宋;color:black;font-size: 2em;\" href=\"");
      out.print(request.getContextPath());
      out.write("/car/getImg?u_card=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.u_card}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">车图一览</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>  \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div> \r\n");
      out.write("    \r\n");
      out.write("    <div class=\"single-product-area\">\r\n");
      out.write("        <div class=\"zigzag-bottom\"></div>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"col-md-8\">\r\n");
      out.write("                    <div class=\"product-content-right\">\r\n");
      out.write("\t                             <div id=\"order_review\" style=\"position: relative;\">\r\n");
      out.write("\t                                 <table class=\"shop_table\" style=\"position: relative;width: 550px;\">\r\n");
      out.write("\t                                     <tfoot>\r\n");
      out.write("\t                                         <tr class=\"shipping\">\r\n");
      out.write("\t                                             <th>订单号</th>\r\n");
      out.write("\t                                             <td><span id=\"o_code\">");
      out.print(RandomUtils.genRandomNum());
      out.write("</span></td>\r\n");
      out.write("\t                                         </tr>\r\n");
      out.write("\t                                         <tr class=\"shipping\">\r\n");
      out.write("\t                                             <th>身份证号</th>\r\n");
      out.write("\t                                             <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.u_card}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("\t                                         </tr>\r\n");
      out.write("\t                                         <tr class=\"shipping\">\r\n");
      out.write("\t                                             <th>驾驶证号</th>\r\n");
      out.write("\t                                             <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.u_jscard}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("\t                                         </tr>\r\n");
      out.write("\t                                         <tr class=\"shipping\">\r\n");
      out.write("\t                                             <th>车牌号码</th>\r\n");
      out.write("\t                                             <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${car.b_code}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("\t                                         </tr>\r\n");
      out.write("\t                                         <tr class=\"shipping\">\r\n");
      out.write("\t                                             <th>日租价</th>\r\n");
      out.write("\t                                             <td id=\"price\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${car.b_price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("\t                                         </tr>\r\n");
      out.write("\t                                         \r\n");
      out.write("\t                                         <tr class=\"shipping\">\r\n");
      out.write("\t                                         \t<th>选择日期</th>\r\n");
      out.write("\t                                         \t<td><span class=\"date_title\" id=\"date1\" \r\n");
      out.write("\t                                         \tstyle=\"width: 200px;border: 1px solid #ccc;border-radius:5px;padding: 8px;\"></span></td>\r\n");
      out.write("\t                                         <tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr class=\"shipping\">\r\n");
      out.write("\t                                             <th>总天数</th>\r\n");
      out.write("\t                                             <td><span id=\"allDay\"></span></td>\r\n");
      out.write("\t\t\t                                 </tr>\r\n");
      out.write("\t\t\t                                 <tr class=\"shipping\">\r\n");
      out.write("\t                                             <th>押金</th>\r\n");
      out.write("\t                                             <td><span id=\"yj\" >￥800</span></td>\r\n");
      out.write("\t\t\t                                 </tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr class=\"shipping\">\r\n");
      out.write("\t                                             <th>总计金额</th>\r\n");
      out.write("\t                                             <td id=\"allPrice\" style=\"color:red;\"></td>\r\n");
      out.write("\t\t\t                                </tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr class=\"shipping\">\r\n");
      out.write("\t                                             <th>提车地点</th>\r\n");
      out.write("\t                                             <td><input id=\"tcdd\" type=\"text\" style=\"border:none;\" readonly=\"readonly\" placeholder=\"请从右边地图选择...\"></td>\r\n");
      out.write("\t                                         </tr>\r\n");
      out.write("\t                                     </tfoot>\r\n");
      out.write("\t                                 </table>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar dateRange1 = new pickerDateRange('date1', {\r\n");
      out.write("\t\taRecent90Days : 'aRecent90Days', //最近90天\r\n");
      out.write("\t\tstartDate: '2017-5-25',\r\n");
      out.write("\t\tendDate: '2017-5-27',\r\n");
      out.write("\t\tneedCompare : false,\r\n");
      out.write("\t\tdefaultText : ' 至 ',\r\n");
      out.write("\t\tautoSubmit : false,\r\n");
      out.write("\t\tinputTrigger : 'input_trigger1',\r\n");
      out.write("\t\ttheme : 'ta'\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("/* 提交订单 */\r\n");
      out.write("function scdd(){\r\n");
      out.write("\t/* jshc(); */\r\n");
      out.write("\r\n");
      out.write("\tvar tcdd = $(\"#tcdd\").val();\r\n");
      out.write("\tif(\"\"==tcdd){\r\n");
      out.write("\t\talert(\"请选择提车地点！\");\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tvar b = confirm(\"你确定预约此车？\");\r\n");
      out.write("\tif(b){\r\n");
      out.write("\t\tvar u_card = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.u_card}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("\t\tvar b_code = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${car.b_code}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar startDate1 = new Date(parseInt((\"/Date(\"+bDateTime+\")/\").substr(6, 13))).toLocaleDateString();\r\n");
      out.write("\t\tvar endDate1 =  new Date(parseInt((\"/Date(\"+eDateTime+\")/\").substr(6, 13))).toLocaleDateString(); \r\n");
      out.write("\t\t//alert(startDate1);\r\n");
      out.write("\t\tvar strstartDate1 = startDate1.split(\"/\");\r\n");
      out.write("\t\tvar startDate=strstartDate1[0]+\"-\"+strstartDate1[1]+\"-\"+strstartDate1[2];\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar strendDate1 = endDate1.split(\"/\");\r\n");
      out.write("\t\tvar endDate=strendDate1[0]+\"-\"+strendDate1[1]+\"-\"+strendDate1[2];\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar biaoxian;\r\n");
      out.write("\t\tif($(\"#baoxian\").is(':checked')){\r\n");
      out.write("\t\t\tbiaoxian=\"已购买\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(!$(\"#baoxian\").is(':checked')){\r\n");
      out.write("\t\t\tbiaoxian=\"未购买\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tvar o_code = $(\"#o_code\").text();\r\n");
      out.write("\t\tvar orderList = b_code+\"!\"+startDate1+\"!\"+endDate1+\"!\"+tcdd+\"!\"+biaoxian+\"!\"+o_code;\r\n");
      out.write("\r\n");
      out.write("\t\twindow.location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/order/makeOrderList?orderList='+orderList+'&u_card='+u_card;\r\n");
      out.write("\t}else{\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function jshc(){\r\n");
      out.write("\tvar price = $(\"#price\").text(); \r\n");
      out.write("\tvar startDate = $(\"#startDate\").val();\r\n");
      out.write("\tvar endDate = $(\"#endDate\").val();\r\n");
      out.write("\r\n");
      out.write("\t/* 设置总天数 */\r\n");
      out.write("\tvar days = getRDate(startDate,endDate);\r\n");
      out.write("\t$(\"#allDay\").html(days);  \r\n");
      out.write("\r\n");
      out.write("\t/* 设置总金额 */\r\n");
      out.write("\t $.post(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/sendVerifyCodeServlet?method=getDate&price=\"+price+\"&days=\"+days,function(data){\r\n");
      out.write("\t\tvar allMoney = data+800;\r\n");
      out.write("\t\t$(\"#allPrice\").html(parseInt(allMoney));\r\n");
      out.write("\t});  \r\n");
      out.write("} \r\n");
      out.write("\r\n");
      out.write("/* 日期相减的天数 */\r\n");
      out.write("function getRDate(sDate,eDate){\r\n");
      out.write("\tvar sArr = sDate.split(\"-\");\r\n");
      out.write("\tvar eArr = eDate.split(\"-\");\r\n");
      out.write("\tvar sRDate = new Date(sArr[0], sArr[1], sArr[2]);\r\n");
      out.write("\tvar eRDate = new Date(eArr[0], eArr[1], eArr[2]);\r\n");
      out.write("\tvar result = (eRDate-sRDate)/(24*60*60*1000);\r\n");
      out.write("\treturn result;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 加载县 */\r\n");
      out.write("$(function(){\r\n");
      out.write("\t$.post(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/province/getProvince\",function(data){\r\n");
      out.write("\t\t$.each(data,function(i, item) {  \r\n");
      out.write("            var statem = \"<option value='\"+item.p_name+\"'>\"+item.p_name+\"</option>\";  \r\n");
      out.write("            $(\"#cityName\").append(statem);  \r\n");
      out.write("        }); \r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("/*查找地方店铺*/\r\n");
      out.write("function queryDf() {\r\n");
      out.write("\tvar province = $(\"#cityName\").val();\r\n");
      out.write("\tif(\"\"==province){\r\n");
      out.write("\t\talert(\"请先选择省份！\");\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\t$.post(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/province/getDf?province=\"+province,function(data){\r\n");
      out.write("\t\t$(\"#cityName2\").html(\"\");\r\n");
      out.write("\t \t$.each(data,function(i, item) {  \r\n");
      out.write("            var statem = \"<option value='\"+item.d_name+\"'>\"+item.d_pname+\"</option>\";  \r\n");
      out.write("            $(\"#cityName2\").append(statem);  \r\n");
      out.write("        });\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 购买保险 */\r\n");
      out.write("function gmbx(){\r\n");
      out.write("\tif($(\"#baoxian\").is(':checked')){\r\n");
      out.write("\t\tvar allprice = $(\"#allPrice\").text();\r\n");
      out.write("\t\tvar all =parseInt(allprice) +35.0;\r\n");
      out.write("\t\t$(\"#allPrice\").html(all);\r\n");
      out.write("\t}\r\n");
      out.write("\tif(!$(\"#baoxian\").is(':checked')){\r\n");
      out.write("\t\tvar allprice = $(\"#allPrice\").text();\r\n");
      out.write("\t\tvar all =parseInt(allprice) -35.0;\r\n");
      out.write("\t\t$(\"#allPrice\").html(all);\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\t                                 \r\n");
      out.write("\t\t\t\t\t\t\t<!-- 地图定位 -->\r\n");
      out.write("\t\t\t\t\t\t\t<div style=\"position:absolute;border: 1px solid #ccc;width:530px;height:430px;left:600px;top:0px;margin: 0px;padding: 0px; \">\r\n");
      out.write("\t\t\t\t\t\t\t\t<select id=\"cityName\" style=\"border:1px solid #ccc;width:60:px;height:25px;\" onchange=\"queryDf()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- 加载县 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"\">--请选择省份--</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t<select id=\"cityName2\" style=\"border:1px solid #ccc;width:60:px;height:25px;\" onchange=\"xianshi()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"\">--请选择店铺--</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"button\" onclick=\"searchCity()\" style=\"background-color: #FFFFFF;margin: 0px;padding: 0px;font-size: 1.3em;font-family: 仿宋;border-radius:5px;\" value=\"查找\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"ditu\" style=\"width:100%;height:100%;\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("                            <div style=\"position:absolute;left:600px;top:470px; \" id=\"payment\">\r\n");
      out.write("                            \t<div style=\"font-family: 楷体;font-size: 1.3em;font-weight: 900;\" class=\"form-row place-order\">\r\n");
      out.write("                                   <input type=\"checkbox\" id=\"baoxian\" name=\"保险\" value=\"checkbox\" onchange=\"gmbx()\" ><a>购买￥35保险</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <br>\r\n");
      out.write("                                <div class=\"form-row place-order\">\r\n");
      out.write("                                   \t<input type=\"button\" onclick=\"scdd()\" value=\"提交\" id=\"place_order\" style=\"font-family: 楷体;font-size: 1.8em;font-weight: 900;width:200px;\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                        </div>                       \r\n");
      out.write("                    </div>                    \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("<script src=\"http://api.map.baidu.com/api?v=1.4\" type=\"text/javascript\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    var map = new BMap.Map(\"ditu\");        //在container容器中创建一个地图,参数container为div的id属性;\r\n");
      out.write("    var point = new BMap.Point(103.79,36.07);    //创建点坐标\r\n");
      out.write("    map.centerAndZoom(point, 12);                //初始化地图，设置中心点坐标和地图级别\r\n");
      out.write("    \r\n");
      out.write("    map.enableScrollWheelZoom();                //激活滚轮调整大小功能\r\n");
      out.write("    map.addControl(new BMap.NavigationControl());    //添加控件：缩放地图的控件，默认在左上角；\r\n");
      out.write("    map.addControl(new BMap.MapTypeControl());        //添加控件：地图类型控件，默认在右上方；\r\n");
      out.write("    map.addControl(new BMap.ScaleControl());        //添加控件：地图显示比例的控件，默认在左下方；\r\n");
      out.write("    map.addControl(new BMap.OverviewMapControl());  //添加控件：地图的缩略图的控件，默认在右下方； TrafficControl   \r\n");
      out.write("    \r\n");
      out.write("    var search = new BMap.LocalSearch(\"中国\", {\r\n");
      out.write("      onSearchComplete: function(result,result2){\r\n");
      out.write("        if (search.getStatus() == BMAP_STATUS_SUCCESS){\r\n");
      out.write("          var res = result.getPoi(0);\r\n");
      out.write("          var point = res.point;\r\n");
      out.write("          map.centerAndZoom(point, 11);\r\n");
      out.write("        }\r\n");
      out.write("      },renderOptions: {  //结果呈现设置，\r\n");
      out.write("        map: map,  \r\n");
      out.write("        autoViewport: true,  \r\n");
      out.write("        selectFirstResult: true \r\n");
      out.write("      } ,onInfoHtmlSet:function(poi,html){//标注气泡内容创建后的回调函数，有了这个，可以简单的改一下返回的html内容了。\r\n");
      out.write("        // alert(html.innerHTML)\r\n");
      out.write("      }//这一段可以不要，只不过是为学习更深层次应用而加入的。\r\n");
      out.write("    });\r\n");
      out.write("    search.search($(\"#cityName2\").val());\r\n");
      out.write("    \r\n");
      out.write("    function searchCity() {\r\n");
      out.write("    \t search.search($(\"#cityName2\").val());\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("    function xianshi() { \r\n");
      out.write("\t\t$(\"#tcdd\").val($(\"#cityName2\").find(\"option:selected\").text());\r\n");
      out.write("\t}\r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("    <div class=\"footer-bottom-area\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-8\">\r\n");
      out.write("                    <div class=\"copyright\">\r\n");
      out.write("                        <p>兰州交通大学.clm&nbsp;&nbsp;&nbsp;<a target=\"_blank\" href=\"#\">登录QQ</a></p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"col-md-4\">\r\n");
      out.write("                    <div class=\"footer-card-icon\">\r\n");
      out.write("                        <i class=\"fa fa-cc-discover\"></i>\r\n");
      out.write("                        <i class=\"fa fa-cc-mastercard\"></i>\r\n");
      out.write("                        <i class=\"fa fa-cc-paypal\"></i>\r\n");
      out.write("                        <i class=\"fa fa-cc-visa\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("   \r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath() );
      out.write("/fore/js/min.js\"></script>\r\n");
      out.write("   <script src=\"");
      out.print(request.getContextPath() );
      out.write("/fore/js/min2.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <!-- jQuery sticky menu -->\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath() );
      out.write("/fore/js/owl.carousel.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath() );
      out.write("/fore/js/jquery.sticky.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <!-- jQuery easing -->\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath() );
      out.write("/fore/js/jquery.easing.1.3.min.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Main Script -->\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath() );
      out.write("/fore/js/main.js\"></script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
