/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.45
 * Generated at: 2018-01-08 11:42:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class orderList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1481687266000L));
    _jspx_dependants.put("jar:file:/D:/renthome/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/carRental_fore/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098682290000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width,initial-scale=0.25\"/>\r\n");
      out.write("    <title>我的订单</title>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Bootstrap -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/fore/css/bootstrap.min.css\">\r\n");
      out.write("    <!-- Font Awesome -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/fore/css/font-awesome.min.css\">\r\n");
      out.write("    <!-- Custom CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/fore/css/owl.carousel.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/fore/style.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/fore/css/responsive.css\">\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath() );
      out.write("/fore/js/jquery-1.8.2.min.js\"></script>\r\n");
      out.write("    <style type=\"text/css\">\r\n");
      out.write("    \t#zt{\r\n");
      out.write("    \t\tmargin: 10px;\r\n");
      out.write("    \t\tfont-family: 楷体;\r\n");
      out.write("    \t\tfont-size: 1.5em;\r\n");
      out.write("    \t\tfont-weight: 900;\r\n");
      out.write("    \t}\r\n");
      out.write("    \t#zt span{\r\n");
      out.write("    \t\tmargin-left: 22px;\r\n");
      out.write("    \t\tborder:1px solid #ccc;\r\n");
      out.write("    \t\tborder-radius:6px;\r\n");
      out.write("    \t\tpadding: 8px;\r\n");
      out.write("    \t}\r\n");
      out.write("    \t#ttr:HOVER{\r\n");
      out.write("    \t\tbackground-color: #ccc;\r\n");
      out.write("    \t}\r\n");
      out.write("    </style>\r\n");
      out.write("    \r\n");
      out.write("<!-- 订单详情隐藏框 -->\r\n");
      out.write("<style>\r\n");
      out.write("#dydd:HOVER{\r\n");
      out.write("\tcolor:red;\r\n");
      out.write("}\r\n");
      out.write(".login-body .xx{\r\n");
      out.write("\tfont-family: 仿宋;\r\n");
      out.write("\tfont-size: 1.2em;\r\n");
      out.write("\tfont-weight: 900px;\r\n");
      out.write("}\r\n");
      out.write(".login-body .xx p label{\r\n");
      out.write("\tcolor:#000000;\r\n");
      out.write("}\r\n");
      out.write(".login-body .xx p span{\r\n");
      out.write("\tcolor:green;\r\n");
      out.write("\tfont-weight: 900;\r\n");
      out.write("}\r\n");
      out.write(".login-body {\r\n");
      out.write("\tpadding: 60px 15px;\r\n");
      out.write("\theight: 148px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".hide-body {\r\n");
      out.write("\tz-index: 9999;\r\n");
      out.write("\tposition: fixed;\r\n");
      out.write("\ttop: 30%;\r\n");
      out.write("\tleft: 40%;\r\n");
      out.write("\twidth: 900px;\r\n");
      out.write("\theight: 600px;\r\n");
      out.write("\tmargin: -180px 0 0 -330px;\r\n");
      out.write("\tborder-radius: 10px;\r\n");
      out.write("\tborder: solid 2px #666;\r\n");
      out.write("\tbackground-color: #fff;\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("\tbox-shadow: 0 0 10px #666;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".close-window {\r\n");
      out.write("\tborder-bottom: 1px solid #ddd;\r\n");
      out.write("\tpadding: 22px;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".bottom {\r\n");
      out.write("\tmargin-top: 250px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".close-window .close {\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("\tcolor: #999;\r\n");
      out.write("\tpadding: 5px;\r\n");
      out.write("\tmargin: -2px -5px -5px;\r\n");
      out.write("\tfont: bold 14px/14px simsun;\r\n");
      out.write("\ttext-shadow: 0 1px 0 #ddd\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".close-window .close:hover {\r\n");
      out.write("\tcolor: #444;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<!-- 订单详情隐藏框 -->\r\n");
      out.write("\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("   <div class=\"header-area\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-8\">\r\n");
      out.write("                    <div class=\"col-md-8\">\r\n");
      out.write("                    <div class=\"user-menu\">\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li>当前用户：</li>\r\n");
      out.write("                        \t<li><a href=\"#\"><i class=\"fa fa-user\"></i>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.u_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</a></li>\r\n");
      out.write("                            <li><a href=\"javascript:exitFun()\"><i class=\"fa fa-user\"></i> 退出</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <script type=\"text/javascript\">\r\n");
      out.write("\t                \tfunction exitFun(){\r\n");
      out.write("\t                \t\tvar b = confirm(\"你确定退出？\");\r\n");
      out.write("\t                \t\tif(b){\r\n");
      out.write("\t                \t\t\twindow.location.href='");
      out.print(request.getContextPath() );
      out.write("/fore/exit.jsp';\r\n");
      out.write("\t                \t\t}else{}\r\n");
      out.write("\t                \t}\r\n");
      out.write("                \t</script>\r\n");
      out.write("                </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div> <!-- End header area -->\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"site-branding-area\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-sm-6\">\r\n");
      out.write("                    <div class=\"logo\">\r\n");
      out.write("                        <h1><a href=\"#\">\r\n");
      out.write("                        \t<img id=\"myLogoImg\" style=\"height: 140px;width: 170px;position: absolute;top: 0px;left:930px;\">\r\n");
      out.write("                        \t</a>\r\n");
      out.write("\t\t\t\t\t\t</h1>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div> \r\n");
      out.write("\r\n");
      out.write("<script src='");
      out.print(request.getContextPath() );
      out.write("/fore/js/jquery-1.7.2.min.js'></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$.post(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/car/getLogoImg\",function(data){\r\n");
      out.write("\t $(\"#myLogoImg\").attr(\"src\",\"/car_img/\"+data);\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"mainmenu-area\" style=\"position: absolute;top: 80px;left:110px;margin: 0;\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"navbar-collapse collapse\" >\r\n");
      out.write("                    <ul class=\"nav navbar-nav\" style=\"border: 1px solid #ccc;border-radius:15px;\">\r\n");
      out.write("                        <li><a style=\"font-family: 仿宋;color:black;font-size: 2em;\" href=\"");
      out.print(request.getContextPath());
      out.write("/car/index/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.u_card}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">首页</a></li>\r\n");
      out.write("                        <li><a style=\"font-family: 仿宋;color:black;font-size: 2em;\" href=\"");
      out.print(request.getContextPath());
      out.write("/user/getUser/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.u_card}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">我的主页</a></li>\r\n");
      out.write("                        <li><a style=\"font-family: 仿宋;color:black;font-size: 2em;\" href=\"");
      out.print(request.getContextPath());
      out.write("/car/getPageCar?u_card=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.u_card}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">汽车查询</a></li>\r\n");
      out.write("                        <li class=\"active\"><a style=\"font-family: 仿宋;color:red;font-size: 2em;\" href=\"");
      out.print(request.getContextPath());
      out.write("/order/getOrders?u_card=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.u_card}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">我的订单</a></li>\r\n");
      out.write("                        <li><a style=\"font-family: 仿宋;color:black;font-size: 2em;\" href=\"");
      out.print(request.getContextPath());
      out.write("/user/talk\">联系客服</a></li>\r\n");
      out.write("                    \t<li><a style=\"font-family: 仿宋;color:black;font-size: 2em;\" href=\"");
      out.print(request.getContextPath());
      out.write("/car/getImg?u_card=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.u_card}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">车图一览</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>  \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div> \r\n");
      out.write("    \r\n");
      out.write("    <div class=\"single-product-area\">\r\n");
      out.write("        <div class=\"zigzag-bottom\"></div>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("\t\t\t\t\t<div style=\"width: 100%;\" role=\"tabpanel\">\r\n");
      out.write("                        <ul class=\"product-tab\" role=\"tablist\">\r\n");
      out.write("                            <li role=\"presentation\" class=\"active\"><a href=\"#home\" aria-controls=\"home\" role=\"tab\" data-toggle=\"tab\">订单列表</a></li>\r\n");
      out.write("                            <li role=\"presentation\"><a href=\"#profile\" aria-controls=\"profile\" role=\"tab\" data-toggle=\"tab\">订单统计</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                        <div class=\"tab-content\">\r\n");
      out.write("                       \t\t<!-- 所有订单 -->\r\n");
      out.write("                            <div role=\"tabpanel\" class=\"tab-pane fade in active\" id=\"home\">\r\n");
      out.write("\t                            <div id=\"zt\">\r\n");
      out.write("\t                       \t\t\t<span id=\"rrr\" onclick=\"yzf()\">已支付 </span>\r\n");
      out.write("\t                       \t\t\t<span onclick=\"wzf()\">未支付</span>\r\n");
      out.write("\t                       \t\t\t<span onclick=\"ytc()\">已提车</span>\r\n");
      out.write("\t                       \t\t\t<span onclick=\"yqx()\">已取消</span>\r\n");
      out.write("\t                       \t\t\t<span onclick=\"yhc()\">已还车</span>\r\n");
      out.write("\t                       \t\t\t<input style=\"margin-left: 60px;\" type=\"text\" id=\"order_code\" placeholder=\"请输入订单号\">\r\n");
      out.write("\t                       \t\t\t<input type=\"button\" onclick=\"cx()\" value=\"查询\">\r\n");
      out.write("\t                       \t\t\t<input style=\"margin-left:40px; \" type=\"button\" value=\"导出订单\"\r\n");
      out.write("\t                       \t\t\tonClick =\"$('#table1').tableExport({type: 'excel', escape: 'false'});\">\r\n");
      out.write("\t                       \t\t</div>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function cx(){\r\n");
      out.write("\tvar o_code=$(\"#order_code\").val();\r\n");
      out.write("\tif(\"\"==o_code||null==o_code){\r\n");
      out.write("\t\talert(\"请输入你要查询的订单号！\"); \r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\twindow.location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/order/cxOrder?o_code='+o_code+'&u_card=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.u_card}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("}\r\n");
      out.write("function yzf(){\r\n");
      out.write("\tvar o_state = \"已支付\";\r\n");
      out.write("\twindow.location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/order/grtOrderByTj?o_state='+o_state+'&u_card=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.u_card}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("}\r\n");
      out.write("function wzf(){\r\n");
      out.write("\tvar o_state = \"未支付\";\r\n");
      out.write("\twindow.location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/order/grtOrderByTj?o_state='+o_state+'&u_card=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.u_card}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("}\r\n");
      out.write("function ytc(){\r\n");
      out.write("\tvar o_state = \"已提车\";\r\n");
      out.write("\twindow.location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/order/grtOrderByTj?o_state='+o_state+'&u_card=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.u_card}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("}\r\n");
      out.write("function yqx(){\r\n");
      out.write("\tvar o_state = \"已取消\";\r\n");
      out.write("\twindow.location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/order/grtOrderByTj?o_state='+o_state+'&u_card=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.u_card}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("}\r\n");
      out.write("function yhc(){\r\n");
      out.write("\tvar o_state = \"已还车\";\r\n");
      out.write("\twindow.location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/order/grtOrderByTj?o_state='+o_state+'&u_card=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.u_card}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script> \r\n");
      out.write("                            \r\n");
      out.write("\t\t\t\t\t\t\t\t<table cellspacing=\"0\" class=\"shop_table cart\" id=\"table1\">\r\n");
      out.write("                                \t<tr class=\"cart_item\">\r\n");
      out.write("                                        <td class=\"product-thumbnail\">订单号</td>\r\n");
      out.write("                                        <td class=\"product-thumbnail\">汽车车牌</td>\r\n");
      out.write("                                        <td class=\"product-thumbnail\">提车日期</td>\r\n");
      out.write("                                        <td class=\"product-thumbnail\">还车日期</td>\r\n");
      out.write("                                        <td class=\"product-thumbnail\">总金额</td>\r\n");
      out.write("                                        <td class=\"product-thumbnail\">保险</td>\r\n");
      out.write("                                        <td class=\"product-thumbnail\">订单状态</td>\r\n");
      out.write("                                        <td class=\"product-thumbnail\">订单处理</td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                    ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                                </table>\r\n");
      out.write("\t\t\t\t            </div>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("/*打印订单*/\r\n");
      out.write("function dydd(o_code,u_name){\r\n");
      out.write("\t$.post(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/order/dyOrderInfo?o_code=\"+o_code,function(data){\r\n");
      out.write("\t\tif(\"1\"==data){\r\n");
      out.write("\t\t\talert(\"你好:【 \"+u_name+\" 】,你的订单与合同下载成功，在D盘下打开！\");\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\talert(\"你好:【 \"+u_name+\" 】,你的订单与合同下载失败，请联系公司！\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/*支付订单：只能支付未支付订单*/\r\n");
      out.write("function payOrder(o_state,o_code){\r\n");
      out.write("\tif(\"未支付\"==o_state){\r\n");
      out.write("\t\tvar b = confirm(\"你确定支付订单？\");\r\n");
      out.write("\t\tif(b){\r\n");
      out.write("\t\t\twindow.location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/order/pay?o_code='+o_code+'&u_card=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.u_card}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("\t\t}else{}\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\talert(\"你的操作有误，请查看你的订单状态!\");\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 查询汽车详情 */\r\n");
      out.write("function queryCarInfo(b_code) {\r\n");
      out.write("\twindow.location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/car/getCarInfo/'+b_code;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/*取消订单：只能取消未支付订单*/\r\n");
      out.write("function qxdd(o_code,o_state){\r\n");
      out.write("\tif(\"未支付\"==o_state){\r\n");
      out.write("\t\tvar b = confirm(\"订单：\"+o_code+\"，你确定取消订单？\");\r\n");
      out.write("\t\tif(b){\r\n");
      out.write("\t\t\twindow.location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/order/qxOrder?o_code='+o_code+'&u_card=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.u_card}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("\t\t}else{}\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\talert(\"你的操作有误，请查看你的订单状态!\");\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\t\t\t                \r\n");
      out.write("                            <!-- 订单统计 -->\r\n");
      out.write("                            <div role=\"tabpanel\" class=\"tab-pane fade\" id=\"profile\">\r\n");
      out.write("                                <div id=\"xs\">\r\n");
      out.write("                               \t\t<span id=\"tj1\"></span>\r\n");
      out.write("                               \t\t<span id=\"tj2\"></span>\r\n");
      out.write("                               \t\t<div style=\"position:absolute;top:380px;left:900px; font-family:楷体;font-size: 1.5em;font-weight: 900;\">\r\n");
      out.write("                               \t\t\t<label><input type=\"radio\" checked=\"checked\" name=\"radio\" onclick=\"fun1()\">支付状态</label>\r\n");
      out.write("                               \t\t\t<br>\r\n");
      out.write("                               \t\t\t<br>\r\n");
      out.write("                               \t\t\t<br>\r\n");
      out.write("                               \t\t\t<label><input type=\"radio\" name=\"radio\" onclick=\"fun2()\">购买保险</label>\r\n");
      out.write("                               \t\t</div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath() );
      out.write("/fore/js/tjJS/jscharts.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(function(){\r\n");
      out.write("\tfunT1();\r\n");
      out.write("\t$(\"#tj1\").show();\r\n");
      out.write("\t$(\"#tj2\").hide();\r\n");
      out.write("});\r\n");
      out.write("function fun1(){\r\n");
      out.write("\t$(\"#tj1\").show();\r\n");
      out.write("\t$(\"#tj2\").hide();\r\n");
      out.write("}\r\n");
      out.write("function fun2(){\r\n");
      out.write("\t$(\"#tj2\").show();\r\n");
      out.write("\t$(\"#tj1\").hide();\r\n");
      out.write("}\r\n");
      out.write("function funT1(){\r\n");
      out.write("\t/* 订单是否支付 */\r\n");
      out.write("\tvar num1 =parseFloat('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${PayOrders}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("') ;\r\n");
      out.write("\tvar num2 =parseFloat('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${NoPayOrders}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("');\r\n");
      out.write("\tvar myData = new Array(['已支付',num1],['未支付',num2]);\r\n");
      out.write("\tvar colors = ['#0066CC', '#FF9900'];\r\n");
      out.write("\tvar myChart = new JSChart('tj1', 'pie');\r\n");
      out.write("\tmyChart.setDataArray(myData);\r\n");
      out.write("\tmyChart.colorizePie(colors);\r\n");
      out.write("\tmyChart.setTitle('订单支付状态统计');\r\n");
      out.write("\tmyChart.setTitleColor('#0066CC');\r\n");
      out.write("\tmyChart.setTitleFontSize(16);\r\n");
      out.write("\tmyChart.setTextPaddingTop(280);\r\n");
      out.write("\tmyChart.setPieValuesDecimals(1);\r\n");
      out.write("\tmyChart.setPieUnitsFontSize(9);\r\n");
      out.write("\tmyChart.setPieValuesFontSize(8);\r\n");
      out.write("\tmyChart.setPieValuesColor('#fff');\r\n");
      out.write("\tmyChart.setPieUnitsColor('#969696');\r\n");
      out.write("\tmyChart.setSize(616, 321);\r\n");
      out.write("\tmyChart.setPiePosition(308, 145);\r\n");
      out.write("\tmyChart.setPieRadius(95);\r\n");
      out.write("\tmyChart.setFlagColor('#fff');\r\n");
      out.write("\tmyChart.setFlagRadius(4);\r\n");
      out.write("\tmyChart.setBackgroundImage('");
      out.print(request.getContextPath() );
      out.write("/fore/img/chart_bg.jpg');\r\n");
      out.write("\tmyChart.draw();\r\n");
      out.write("\r\n");
      out.write("\t/* 订单购买了保险 */\r\n");
      out.write("\tvar num3 =parseFloat('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BXOrders}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("') ;\r\n");
      out.write("\tvar num4 =parseFloat('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${NoBXOrders}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("');\r\n");
      out.write("\tvar myData2 = new Array(['有保险',num3],['无保险',num4]);\r\n");
      out.write("\tvar colors2 = ['#99CCFF','#AF0202'];\r\n");
      out.write("\tvar myChart2 = new JSChart('tj2', 'bar');\r\n");
      out.write("\tmyChart2.setDataArray(myData2);\r\n");
      out.write("\tmyChart2.colorizeBars(colors2);\r\n");
      out.write("\tmyChart2.setTitle('是否购买过保险');\r\n");
      out.write("\tmyChart2.setTitleColor('#009966');\r\n");
      out.write("\tmyChart2.setAxisNameX('购买保险状态');\r\n");
      out.write("\tmyChart2.setAxisNameY('订单数目');\r\n");
      out.write("\tmyChart2.setAxisColor('#009966');\r\n");
      out.write("\tmyChart2.setAxisNameFontSize(16);\r\n");
      out.write("\tmyChart2.setAxisNameColor('#999');\r\n");
      out.write("\tmyChart2.setAxisValuesColor('#7E7E7E');\r\n");
      out.write("\tmyChart2.setBarValuesColor('#7E7E7E');\r\n");
      out.write("\tmyChart2.setAxisPaddingTop(60);\r\n");
      out.write("\tmyChart2.setAxisPaddingRight(140);\r\n");
      out.write("\tmyChart2.setAxisPaddingLeft(150);\r\n");
      out.write("\tmyChart2.setAxisPaddingBottom(50);\r\n");
      out.write("\tmyChart2.setTextPaddingLeft(105);\r\n");
      out.write("\tmyChart2.setTitleFontSize(11);\r\n");
      out.write("\tmyChart2.setBarBorderWidth(1);\r\n");
      out.write("\tmyChart2.setBarBorderColor('#009966');\r\n");
      out.write("\tmyChart2.setBarSpacingRatio(50);\r\n");
      out.write("\tmyChart2.setGrid(false);\r\n");
      out.write("\tmyChart2.setSize(616, 321);\r\n");
      out.write("\tmyChart2.setBackgroundImage('");
      out.print(request.getContextPath());
      out.write("/fore/img/chart_bg.jpg');\r\n");
      out.write("\tmyChart2.draw();\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("    <div class=\"footer-bottom-area\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-8\">\r\n");
      out.write("                    <div class=\"copyright\">\r\n");
      out.write("                        <p>兰州交通大学.clm&nbsp;&nbsp;&nbsp;<a target=\"_blank\" href=\"#\">登录QQ</a></p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"col-md-4\">\r\n");
      out.write("                    <div class=\"footer-card-icon\">\r\n");
      out.write("                        <i class=\"fa fa-cc-discover\"></i>\r\n");
      out.write("                        <i class=\"fa fa-cc-mastercard\"></i>\r\n");
      out.write("                        <i class=\"fa fa-cc-paypal\"></i>\r\n");
      out.write("                        <i class=\"fa fa-cc-visa\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("   \r\n");
      out.write("   <script src=\"");
      out.print(request.getContextPath() );
      out.write("/fore/js/min.js\"></script>\r\n");
      out.write("   <script src=\"");
      out.print(request.getContextPath() );
      out.write("/fore/js/min2.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <!-- jQuery sticky menu -->\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath() );
      out.write("/fore/js/owl.carousel.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath() );
      out.write("/fore/js/jquery.sticky.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <!-- jQuery easing -->\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath() );
      out.write("/fore/js/jquery.easing.1.3.min.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Main Script -->\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath() );
      out.write("/fore/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 订单详情隐藏框 -->\r\n");
      out.write("<div class=\"hide-body\" id=\"jietu\">\r\n");
      out.write("\t<div class=\"close-window\">\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\t\t<a href=\"javascript:;\" title=\"关闭\" class=\"close\">×</a>\r\n");
      out.write("\t\t<h3 align=\"center\">订单号：<span id=\"o_code\"></span></h3>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"login-body\" style=\"background: url('../fore/img/qczl.jpg') no-repeat right bottom;\">\r\n");
      out.write("\t\t<div style=\"float: left;margin-left: 50px;\">\r\n");
      out.write("\t\t\t<img alt=\"\" src=\"/car_img/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.u_img}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" style=\"width:120px; height: 150px;border: 1px solid #CCCCCC;border-radius:5px; \">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"xx\" style=\"float: left;margin-left: 30px;\">\r\n");
      out.write("\t\t\t<p><label>姓名:</label><span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.u_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("\t\t\t<p><label>身份证号:</label><span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.u_card}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span></p>\r\n");
      out.write("\t\t\t<p><label>驾驶证号:</label><span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.u_jscard}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span></p>\r\n");
      out.write("\t\t\t<p><label>汽车车牌:</label><span id=\"b_code\"></span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"xx\" style=\"float: left;margin-left: 30px;\">\r\n");
      out.write("\t\t\t<p><label>提车日期:</label><span id=\"start_date\"></span></p>\r\n");
      out.write("\t\t\t<p><label>还车日期:</label><span id=\"end_date\"></span></p>\r\n");
      out.write("\t\t\t<p><label>总天数:</label><span id=\"days\"></span>\r\n");
      out.write("\t\t\t<p><label>提车地点:</label><span id=\"d_pname\"></span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"xx\" style=\"float: left;margin-left: 30px;\">\r\n");
      out.write("\t\t\t<p><label>￥35保险:</label><span id=\"o_bx\"></span></p>\r\n");
      out.write("\t\t\t<p><label>日租价:</label><span id=\"b_price\"></span></p>\r\n");
      out.write("\t\t\t<p><label>总金额:</label><span style=\"color:red;font-weight:900;\" id=\"allMoney\"></span></p>\r\n");
      out.write("\t\t\t<p><label>订单状态:</label><span style=\"color:red;font-weight:900;\" id=\"o_state\"></span></p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<div style=\"margin-top:15px; margin-left: 60px;\">\r\n");
      out.write("\t\t\t\t<img id=\"biaozhi\" alt=\"\" src=\"\" style=\"width:90px;height:90px;border: 1px solid #CCCCCC;border-radius:5px; \">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div style=\"margin-top:15px; margin-left: 60px;\">\r\n");
      out.write("\t\t\t\t<img id=\"type\" alt=\"\" src=\"\" style=\"width:90px;height: 90px;border: 1px solid #CCCCCC;border-radius:5px; \">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div style=\"position:absolute;top:300px;left:222px; width:600px;height:200px;border: 1px solid #CCCCCC;border-radius:5px; \">\r\n");
      out.write("\t\t\t<marquee  behavior=\"alternate\" onmouseover=\"this.stop();\" onmouseout=\"this.start();\">\r\n");
      out.write("\t\t\t\t<img id=\"car_img1\" alt=\"\" src=\"\" style=\"margin:7px; width:210px;height: 180px;border: 1px solid #CCCCCC;border-radius:5px; \">\r\n");
      out.write("\t\t\t\t<img id=\"car_img2\" alt=\"\" src=\"\" style=\"margin:7px; width:210px;height: 180px;border: 1px solid #CCCCCC;border-radius:5px; \">\r\n");
      out.write("\t\t\t\t<img id=\"car_img3\" alt=\"\" src=\"\" style=\"margin:7px; width:210px;height: 180px;border: 1px solid #CCCCCC;border-radius:5px; \">\r\n");
      out.write("\t\t\t\t<img id=\"car_img4\" alt=\"\" src=\"\" style=\"margin:7px; width:210px;height: 180px;border: 1px solid #CCCCCC;border-radius:5px; \">\r\n");
      out.write("\t\t\t</marquee>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"bottom\">\r\n");
      out.write("\t<br>\r\n");
      out.write("\t\t<hr>\r\n");
      out.write("\t\t<h3 align=\"center\">风行天下汽车租赁系统欢迎你！ \r\n");
      out.write("\t\t\t<span style=\"position:absolute;right:10px;border:1px solid #ccc;font-weight:900;\r\n");
      out.write("\t\t\tborder-radius:6px;padding:4px; font-family: 楷体;font-size:0.9em;\" \r\n");
      out.write("\t\t\tonClick =\"$('#jietu').tableExport({type: 'png', escape: 'false'});\">保存截图</span>\r\n");
      out.write("\t\t</h3>\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"uploadfileRealPath\">\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- 订单详情隐藏框 -->\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath() );
      out.write("/fore/js/html2canvas.js\"></script>  \r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath() );
      out.write("/fore/js/swfobject.js\"></script>  \r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath() );
      out.write("/fore/js/jquery.base64.js\"></script>  \r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath() );
      out.write("/fore/js/tableExport.js\"></script>  \r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath() );
      out.write("/fore/js/webtoolkit.sprintf.js\"></script>  \r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath() );
      out.write("/fore/js/jspdf.js\"></script>  \r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath() );
      out.write("/fore/js/Base64.js\"></script>  \r\n");
      out.write("<script>\r\n");
      out.write("function funXq(o_code){\r\n");
      out.write("\t/* Ajax实现异步加载订单，并给表单设置值 */\r\n");
      out.write("\t$.post(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/order/orderInfo?o_code=\"+o_code,function(data){\r\n");
      out.write("\t\t$(\"#o_code\").text(o_code)\r\n");
      out.write("\t\t$(\"#b_code\").html(data.b_code);\r\n");
      out.write("\t\t$(\"#b_price\").html(data.b_price);\r\n");
      out.write("\t\t$(\"#start_date\").html(data.start_date);\r\n");
      out.write("\t\t$(\"#end_date\").html(data.end_date);\r\n");
      out.write("\t\t$(\"#days\").html(data.days);\r\n");
      out.write("\t\t$(\"#allMoney\").html(\"￥\"+(data.allMoney));\r\n");
      out.write("\t\t$(\"#o_bx\").html(data.o_bx);\r\n");
      out.write("\t\t$(\"#o_state\").html(data.o_state);\r\n");
      out.write("\t\t$(\"#d_pname\").html(data.diqu.d_pname); \r\n");
      out.write("\r\n");
      out.write("\t\t$(\"#type\").attr(\"src\",\"/car_img/\"+data.type.t_img); \r\n");
      out.write("\t\t$(\"#biaozhi\").attr(\"src\",\"/car_img/\"+data.biaozhi.b_img); \r\n");
      out.write("\r\n");
      out.write("\t\t$(\"#car_img1\").attr(\"src\",\"/car_img/\"+data.carImage.img1); \r\n");
      out.write("\t\t$(\"#car_img2\").attr(\"src\",\"/car_img/\"+data.carImage.img2); \r\n");
      out.write("\t\t$(\"#car_img3\").attr(\"src\",\"/car_img/\"+data.carImage.img3); \r\n");
      out.write("\t\t$(\"#car_img4\").attr(\"src\",\"/car_img/\"+data.carImage.img4); \r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("jQuery(document).ready(function($) {\r\n");
      out.write("\t$('.xq').click(function() { //jquery的点击事件 \r\n");
      out.write("\t\t$('.hide-body').slideDown(200);//将隐藏的窗口div显示出来 \r\n");
      out.write("\t});\r\n");
      out.write("\t$('.close-window .close').click(function() {\r\n");
      out.write("\t\t$('.hide-body').slideUp(200);//将显示的窗口隐藏起来 \r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/orderList.jsp(233,36) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("o");
      // /WEB-INF/views/orderList.jsp(233,36) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${orders}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                                    \t<tr class=\"cart_item\" id=\"ttr\">\r\n");
            out.write("\t                                        <td class=\"product-thumbnail\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.o_code }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t                                        <td onclick=\"queryCarInfo('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.b_code}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("')\" class=\"product-thumbnail\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.b_code}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t                                        <td class=\"product-thumbnail\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.start_date}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t                                        <td class=\"product-thumbnail\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.end_date}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t                                        <td class=\"product-thumbnail\" style=\"color:red;font-size: 1.3em;font-weight:900;\">￥");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.allMoney}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t                                        <td class=\"product-thumbnail\" >\r\n");
            out.write("\t                                        \t<span style=\"border-radius:5px; border:1px solid #99CC00;background-color:#FFFFCC; font-family:仿宋;font-size:1.2em;color:blue;font-weight: 900;\">\r\n");
            out.write("\t                                        \t\t");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.o_bx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\r\n");
            out.write("\t                                        \t</span>\r\n");
            out.write("\t                                        </td>\r\n");
            out.write("\t                                        <td class=\"product-thumbnail\">\r\n");
            out.write("\t                                        \t<span style=\"border-radius:5px; border:1px solid #99CCFF;background-color:#FFFF99; font-family:仿宋;font-size:1.2em;color:#9933FF;font-weight: 900;\">\r\n");
            out.write("\t                                        \t\t ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.o_state}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\r\n");
            out.write("\t                                        \t</span>\r\n");
            out.write("\t                                        </td>\r\n");
            out.write("\t                                        <td class=\"product-thumbnail\">\r\n");
            out.write("\t                                       \t\t");
            if (_jspx_meth_c_005fif_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("\t                                        \t");
            if (_jspx_meth_c_005fif_005f1(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("\t                                        \t");
            if (_jspx_meth_c_005fif_005f2(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("\t                                        </td>\r\n");
            out.write("                                   \t    </tr>\r\n");
            out.write("                                    ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/orderList.jsp(251,42) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${'未支付'==o.o_state || '已取消'==o.o_state || '已还车'==o.o_state || '已提车'==o.o_state}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t                                        \t<a class=\"xq\" onclick=\"funXq('");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.o_code }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("')\" href=\"javascript:;\" style=\"text-decoration:none;border-radius:5px; border:1px solid #99CCFF;background-color:#99CC99; font-family:楷体;font-size:1.3em;color:blue;font-weight: 900;\">详情</a>\r\n");
          out.write("\t                                        \t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/orderList.jsp(254,42) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${'未支付'==o.o_state }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t                                        \t<a href=\"#\" onclick=\"qxdd('");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.o_code }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('\'');
          out.write(',');
          out.write('\'');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.o_state}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("')\" style=\"text-decoration:none;border-radius:5px; border:1px solid #99CCFF;background-color:#FFCCFF; font-family:楷体;font-size:1.3em;color:#9933FF;font-weight: 900;\">取消</a>\r\n");
          out.write("\t                                        \t<a href=\"#\" onclick=\"payOrder('");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.o_state }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('\'');
          out.write(',');
          out.write('\'');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.o_code }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("')\" style=\"text-decoration:none;border-radius:5px; border:1px solid #99CCFF;background-color:#FFFFCC; font-family:楷体;font-size:1.3em;color:red;font-weight: 900;\">付款</a>\r\n");
          out.write("\t                                        \t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/orderList.jsp(258,42) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${'已支付'==o.o_state }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t                                        \t<a class=\"xq\" onclick=\"funXq('");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.o_code }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("')\" href=\"javascript:;\" style=\"text-decoration:none;border-radius:5px; border:1px solid #99CCFF;background-color:#99CC99; font-family:楷体;font-size:1.3em;color:blue;font-weight: 900;\">详情</a>\r\n");
          out.write("\t                                        \t<a href=\"#\" onclick=\"dydd('");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.o_code }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('\'');
          out.write(',');
          out.write('\'');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.u_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("')\" style=\"text-decoration:none;border-radius:5px; border:1px solid #99CCFF;background-color:#FFFFCC; font-family:楷体;font-size:1.3em;color:green;font-weight: 900;\">下载合同</a>\r\n");
          out.write("\t                                        \t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }
}
