/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.45
 * Generated at: 2018-01-08 11:43:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class payOrder_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width,initial-scale=0.25\"/>\r\n");
      out.write("<title>个人详情</title>\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/fore/css/bootstrap.min.css\">\r\n");
      out.write("<!-- Font Awesome -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/fore/css/font-awesome.min.css\">\r\n");
      out.write("<!-- Custom CSS -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/fore/css/owl.carousel.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/fore/style.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/fore/css/responsive.css\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".yh{\r\n");
      out.write("\tfloat:left;\r\n");
      out.write("\tfont-family: 楷体;\r\n");
      out.write("\tfont-size: 1.3em;\r\n");
      out.write("\tfont-weight: 900;\r\n");
      out.write("\twidth: 170px;\r\n");
      out.write("\theight: 30px;\r\n");
      out.write("}\r\n");
      out.write(".yh input{\r\n");
      out.write("\twidth: 15px;\r\n");
      out.write("\theight: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 二维码放大 */\r\n");
      out.write("#qrcodeTable{  \r\n");
      out.write("         cursor: pointer;  \r\n");
      out.write("         transition: all 1.2s;  \r\n");
      out.write(" }  \r\n");
      out.write("#qrcodeTable:hover{  \r\n");
      out.write("     transform: scale(1.6);  \r\n");
      out.write(" }  \r\n");
      out.write(" \r\n");
      out.write("#qrcodeCanvas{  \r\n");
      out.write("         cursor: pointer;  \r\n");
      out.write("         transition: all 1.2s;  \r\n");
      out.write(" }  \r\n");
      out.write("#qrcodeCanvas:hover{  \r\n");
      out.write("     transform: scale(1.6);  \r\n");
      out.write(" }  \r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"header-area\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-8\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-8\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"user-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>当前用户：</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-user\"></i>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.u_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"javascript:exitFun()\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-user\"></i> 退出</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t                \tfunction exitFun(){\r\n");
      out.write("\t\t                \t\tvar b = confirm(\"你确定退出？\");\r\n");
      out.write("\t\t                \t\tif(b){\r\n");
      out.write("\t\t                \t\t\twindow.location.href='");
      out.print(request.getContextPath());
      out.write("/fore/exit.jsp';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t} else {}\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- End header area -->\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"site-branding-area\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-sm-6\">\r\n");
      out.write("                    <div class=\"logo\">\r\n");
      out.write("                        <h1><a href=\"#\">\r\n");
      out.write("                        \t<img id=\"myLogoImg\" style=\"height: 140px;width: 170px;position: absolute;top: 0px;left:930px;\">\r\n");
      out.write("                        \t</a>\r\n");
      out.write("\t\t\t\t\t\t</h1>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div> \r\n");
      out.write("\r\n");
      out.write("<script src='");
      out.print(request.getContextPath() );
      out.write("/fore/js/jquery-1.7.2.min.js'></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$.post(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/car/getLogoImg\",function(data){\r\n");
      out.write("\t $(\"#myLogoImg\").attr(\"src\",\"/car_img/\"+data);\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"mainmenu-area\" style=\"position: absolute;top: 80px;left:110px;margin: 0;\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"navbar-collapse collapse\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"nav navbar-nav\" style=\"border: 1px solid #ccc;border-radius:15px;\">\r\n");
      out.write("\t\t\t\t\t\t<li><a style=\"font-family: 仿宋; color: black; font-size: 2em;\" href=\"");
      out.print(request.getContextPath());
      out.write("/car/index/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.u_card}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">首页</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a style=\"font-family: 仿宋; color: black; font-size: 2em;\" href=\"");
      out.print(request.getContextPath());
      out.write("/user/getUser/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.u_card}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">我的主页</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a style=\"font-family: 仿宋; color: black; font-size: 2em;\" href=\"");
      out.print(request.getContextPath());
      out.write("/car/getPageCar?u_card=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.u_card}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">汽车查询</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a style=\"font-family: 仿宋; color: black; font-size: 2em;\" href=\"");
      out.print(request.getContextPath());
      out.write("/order/getOrders?u_card=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.u_card}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">我的订单</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"active\"><a style=\"font-family: 仿宋; color: red; font-size: 2em;\" href=\"#\">订单支付</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a style=\"font-family: 仿宋; color: black; font-size: 2em;\" href=\"");
      out.print(request.getContextPath());
      out.write("/user/talk\">联系客服</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<div class=\"single-product-area\">\r\n");
      out.write("\t\t<div class=\"zigzag-bottom\"></div>\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div style=\"position: relative; top: -35px;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div role=\"tabpanel\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"product-tab\" role=\"tablist\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li role=\"presentation\" class=\"active\"><a href=\"#home\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\taria-controls=\"home\" role=\"tab\" data-toggle=\"tab\">网上在线支付</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li role=\"presentation\"><a href=\"#profile\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\taria-controls=\"profile\" role=\"tab\" data-toggle=\"tab\">扫码支付</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"tab-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- 在线支付 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div role=\"tabpanel\" class=\"tab-pane fade in active\" id=\"home\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div style=\"margin-left: 100px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<form action=\"");
      out.print(request.getContextPath() );
      out.write("/paymentServlet\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div style=\"background-color: #ccc;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label>订单号：</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input name=\"orderId\" readonly=\"readonly\" style=\"border: none;font-size: 1.4em;width: 400px;background-color: #ccc;\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${orderInfo.o_code}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label style=\"margin-left: 40px;\">应支付：</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input name=\"amount\" readonly=\"readonly\" style=\"border: none;font-size: 1.5em;color: red;background-color: #ccc;\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${orderInfo.allMoney+800}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div style=\"border: 1px solid #ccc;padding-left: 10px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"yh\"><input type=\"radio\" name=\"pd_FrpId\" value=\"CCB-NET\" checked=\"checked\">中国建设银行</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"yh\"><input type=\"radio\" name=\"pd_FrpId\" value=\"ICBC-NET\">中国工商银行</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"yh\"><input type=\"radio\" name=\"pd_FrpId\" value=\"ABC-NET\">农业银行 </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"yh\"><input type=\"radio\" name=\"pd_FrpId\" value=\"CMBCHINA-NET\">招商银行</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"yh\"><input type=\"radio\" name=\"pd_FrpId\" value=\"ABC-NET-B2C\">中国农业银行</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"yh\"><input type=\"radio\" name=\"pd_FrpId\" value=\"BCCB-NET-B2C\">北京银行</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t    <br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t    <br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"yh\"><input type=\"radio\" name=\"pd_FrpId\" value=\"BOCO-NET-B2C\">交通银行 </div>      \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"yh\"><input type=\"radio\" name=\"pd_FrpId\" value=\"NJCB-NET-B2C\">南京银行 </div>      \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"yh\"><input type=\"radio\" name=\"pd_FrpId\" value=\"CMBC-NET-B2C\">中国民生银行 </div>      \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"yh\"> <input type=\"radio\" name=\"pd_FrpId\" value=\"CMBC-NET-B2C\">光大银行</div>      \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"yh\"><input type=\"radio\" name=\"pd_FrpId\" value=\"BOC-NET-B2C\">中国银行 </div>      \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"yh\"><input type=\"radio\" name=\"pd_FrpId\" value=\"PINGANBANK-NET\">平安银行</div>      \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t    <br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t    <br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"yh\"><input type=\"radio\" name=\"pd_FrpId\" value=\"CBHB-NET-B2C\">渤海银行</div>      \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"yh\"><input type=\"radio\" name=\"pd_FrpId\" value=\"HKBEA-NET-B2C\">东亚银行</div>      \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"yh\"><input type=\"radio\" name=\"pd_FrpId\" value=\"NBCB-NET-B2C\">宁波银行</div>      \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"yh\"><input type=\"radio\" name=\"pd_FrpId\" value=\"SDB-NET-B2C\">深圳发展银行</div>      \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"yh\"><input type=\"radio\" name=\"pd_FrpId\" value=\"ECITIC-NET-B2C\">中信银行</div>      \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"yh\"><input type=\"radio\" name=\"pd_FrpId\" value=\"ECITIC-NET-B2C\">广发银行</div>      \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t    <br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t    <br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"yh\"><input type=\"radio\" name=\"pd_FrpId\" value=\"SHB-NET-B2C\">上海银行</div>      \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"yh\"><input type=\"radio\" name=\"pd_FrpId\" value=\"SPDB-NET-B2C\">上海浦发银行</div>      \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"yh\"><input type=\"radio\" name=\"pd_FrpId\" value=\"POST-NET-B2C\">中国邮政</div>      \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"yh\"><input type=\"radio\" name=\"pd_FrpId\" value=\"HZBANK-NET-B2C\">杭州银行 </div>      \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"yh\"><input type=\"radio\" name=\"pd_FrpId\" value=\"HXB-NET-B2C\">华夏银行</div>      \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"yh\"><input type=\"radio\" name=\"pd_FrpId\" value=\"CZ-NET-B2C\">浙商银行</div>      \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t    <br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"yh\"><input type=\"radio\" name=\"pd_FrpId\" value=\"SZX-NET\">神州行 </div>      \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"yh\"><input type=\"radio\" name=\"pd_FrpId\" value=\"QQCARD-NET\">Q币卡 </div>      \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"yh\"><input type=\"radio\" name=\"pd_FrpId\" value=\"TELECOM-NET\">电信卡</div>  \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"submit\" value=\"确认支付\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/fore/js/jquery-1.8.2.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/fore/js/jquery.min.js\" type=\"text/javascript\"></script>  \r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/fore/js/jquery.qrcode.js\" type=\"text/javascript\"></script>  \r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/fore/js/qrcode.js\" type=\"text/javascript\"></script>  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- 微信扫码 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div role=\"tabpanel\" class=\"tab-pane fade\" id=\"profile\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div style=\"float: left;margin-left: 200px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<h2 style=\"text-align: center;\">微信</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div id=\"qrcodeTable\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<img style=\"width: 256px;height: 256px;\" alt=\"\" src=\"");
      out.print(request.getContextPath() );
      out.write("/fore/pay/wx.jpg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div style=\"float: left;margin-left: 200px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<h2 style=\"text-align: center;\">支付宝</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div id=\"qrcodeCanvas\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<img style=\"width: 256px;height: 256px;\" alt=\"\" src=\"");
      out.print(request.getContextPath() );
      out.write("/fore/pay/zfb.jpg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("<script>\r\n");
      out.write("/* jQuery('#qrcodeTable').qrcode({\r\n");
      out.write("\trender\t: \"table\",\r\n");
      out.write("\ttext\t: \"https://open.weixin.qq.com/connect/oauth2/authorize\"\r\n");
      out.write("});\t */\r\n");
      out.write("/* jQuery('#qrcodeCanvas').qrcode({\r\n");
      out.write("\ttext\t: \"https://openapi.alipay.com/gateway.do\"\r\n");
      out.write("});\t */\r\n");
      out.write("</script>\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t<div class=\"footer-bottom-area\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-8\">\r\n");
      out.write("\t\t\t\t\t<div class=\"copyright\">\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t兰州交通大学.clm&nbsp;&nbsp;&nbsp;<a target=\"_blank\" href=\"#\">登录QQ</a>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t\t\t\t<div class=\"footer-card-icon\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-cc-discover\"></i> <i class=\"fa fa-cc-mastercard\"></i>\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-cc-paypal\"></i> <i class=\"fa fa-cc-visa\"></i>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/fore/js/min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/fore/js/min2.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- jQuery sticky menu -->\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/fore/js/owl.carousel.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/fore/js/jquery.sticky.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- jQuery easing -->\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/fore/js/jquery.easing.1.3.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Main Script -->\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/fore/js/main.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
