/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.45
 * Generated at: 2018-01-08 02:04:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.fore;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class frist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>游客页面</title>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width,initial-scale=0.25\"/>\r\n");
      out.write("\r\n");
      out.write("<link href=\"");
      out.print(request.getContextPath() );
      out.write("/fore/css/frist/css/style.css\" rel=\"stylesheet\" />\r\n");
      out.write("<style>\r\n");
      out.write("body{\r\n");
      out.write("\tbackground-color: #CCFFFF;\r\n");
      out.write("}\r\n");
      out.write("#dl:HOVER{\r\n");
      out.write("\tcolor:red;\r\n");
      out.write("}\r\n");
      out.write("#imgg{  \r\n");
      out.write("    cursor: pointer;  \r\n");
      out.write("    transition: all 1.3s;  \r\n");
      out.write("}  \r\n");
      out.write("#imgg:hover{  \r\n");
      out.write("    transform: scale(1.4);  \r\n");
      out.write("}  \r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script src='");
      out.print(request.getContextPath() );
      out.write("/fore/css/frist/js/jquery.min.js'></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div style=\"position:inherit ;color: black;background-color:green;height: 50px;\">\r\n");
      out.write("<marquee style=\"padding-top: 5px;\"> <h4 style=\"font-family:楷体;font-size: 2.2em;font-weight: 900;color:red;\">欢迎来到汽车租赁系统！</h4></marquee>\r\n");
      out.write("<div style=\"background-color: #99CCFF;position: absolute;top:0px;right: 0px;height: 50px;width: 180px;text-align: center;padding-top: 10px;\">\r\n");
      out.write("<a id=\"dl\" href=\"");
      out.print(request.getContextPath() );
      out.write("/fore/login.jsp\" style=\"font-family:仿宋;font-weight: 900;font-size: 1.6em;text-decoration: none;border:1px solid #FFF;border-radius:8px;margin-top: 15px;\">登录</a>\r\n");
      out.write("\r\n");
      out.write("<a id=\"dl\" href=\"");
      out.print(request.getContextPath() );
      out.write("/user/registerJsp\" style=\"font-family:仿宋;font-weight: 900;font-size: 1.6em;text-decoration: none;border:1px solid #FFF;border-radius:8px;margin-top: 15px;margin-left: 20px;\">注册</a>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"cubeTransition\">\r\n");
      out.write("\r\n");
      out.write("<!-- 111 -->\r\n");
      out.write("<div class=\"page1\">\r\n");
      out.write("<h2 style=\"position: relative;top:30px;\">\r\n");
      out.write("<video id=\"myVideo\" src=\"");
      out.print(request.getContextPath() );
      out.write("/fore/video/fhqc.mp4\" preload=\"auto\" poster=\"");
      out.print(request.getContextPath() );
      out.write("/fore/img/fll.jpg\" controls=\"controls\" style=\"border:12px solid #ccc;border-radius:10px;height:480px;width:852px;padding: 0px;\">\r\n");
      out.write("</video>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$.post(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/car/getVideo\",function(data){\r\n");
      out.write("\t $(\"#myVideo\").attr(\"src\",\"/car_img/\"+data);\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</h2>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- 2222 -->\r\n");
      out.write("<div style=\"background-color: #66CC99;\" class=\"page2\">\r\n");
      out.write("<h2>\r\n");
      out.write("<i style=\"color:green; font-size: 0.43em;font-family:楷体; position: absolute;top:-158px;left: 70px;\">租<br>车<br>流<br>程<br>介<br>绍</i>\r\n");
      out.write("<img usemap=\"#mymap\" style=\"position: absolute;top:-140px;left:180px;height:330px;width:700px;\" src=\"");
      out.print(request.getContextPath() );
      out.write("/fore/img/yylc.png\">\r\n");
      out.write("<map name=\"mymap\">\r\n");
      out.write("<area shape = \"rect\" coords=\"150,5,291,40\"   href=\"#\" onclick=\"zcFun()\"/>\r\n");
      out.write("<area shape = \"rect\" coords=\"150,200,291,240\" href=\"#\" onclick=\"dlFun()\"/>\r\n");
      out.write("<area shape = \"rect\" coords=\"362,109,462,133\" href=\"#\" onclick=\"cxqcFun()\"/>\r\n");
      out.write("<area shape = \"rect\" coords=\"361,180,464,200\" href=\"#\" onclick=\"grzyFun()\"/>\r\n");
      out.write("<area shape = \"rect\" coords=\"361,245,462,273\" href=\"#\" onclick=\"yyqcFun()\"/>\r\n");
      out.write("<area shape = \"rect\" coords=\"358,302,459,326\" href=\"#\" onclick=\"lxkfFun()\"/>\r\n");
      out.write("<area shape = \"rect\" coords=\"550,208,655,240\" href=\"#\" onclick=\"qxFun()\"/>\r\n");
      out.write("<area shape = \"rect\" coords=\"550,269,655,300\" href=\"#\" onclick=\"zfFun()\"/>\r\n");
      out.write("</map>\r\n");
      out.write("<textarea id=\"in\" style=\"border:none;background-color: #66CC99;position: absolute;top:-140px;right: 90px;width:320px;height: 340px;font-family:楷体;font-size: 0.275em;font-weight: 900;color:green;\">\r\n");
      out.write("新用户注册\r\n");
      out.write("1.用户必须输入相应的值！\r\n");
      out.write("2.填入的手机号要接收短信验证码！\r\n");
      out.write("3.注册成功后即可登录！\r\n");
      out.write("</textarea>\r\n");
      out.write("<i style=\"color:green; font-size: 0.25em;font-family:楷体; position: absolute;top: 220px;left: 70px;\"><br>个<br>人<br>号</i>\r\n");
      out.write("<img id=\"imgg\" style=\"width: 150px;height: 150px;position: absolute;top: 220px;left:120px;\" title=\"个人号\" src=\"");
      out.print(request.getContextPath() );
      out.write("/fore/img/erweima.jpg\">\r\n");
      out.write("<i style=\"color:green; font-size: 0.25em;font-family:楷体; position: absolute;top: 220px;left:300px;\"><br>公<br>众<br>号</i>\r\n");
      out.write("<img id=\"imgg\" style=\"width: 150px;height: 150px;position: absolute;top: 220px;left:350px;\" title=\"公众号\" src=\"");
      out.print(request.getContextPath() );
      out.write("/fore/img/ewm.jpg\">\r\n");
      out.write("<i style=\"color:green; font-size: 0.27em;font-family:楷体; position: absolute;top: 230px;left:525px;\">\r\n");
      out.write("个人号：系统、租车流程介绍，积分兑换等功能\r\n");
      out.write("<br><br>\r\n");
      out.write("公众号：翻译、天气预报、新车、优惠推荐等功能\r\n");
      out.write("</i>\r\n");
      out.write("</h2>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- 3333 -->\r\n");
      out.write("<div style=\"background-color: #246;\" class=\"page3\">\r\n");
      out.write("<label id=\"flashcontent\" style=\"position:absolute;left:315px;top:80px; border: 10px solid #ccc;border-radius:10px ;\"></label>\r\n");
      out.write("<label style=\"position:absolute;left:440px;top:500px;font-family:楷体;font-size: 0.35em;font-weight: 900;\">\r\n");
      out.write("<label id=\"mkl\"><input type=\"radio\" name=\"sand\" checked=\"checked\" id=\"slr\" onclick=\"sFun()\">迈凯伦内观图</label>\r\n");
      out.write("<label id=\"adl\"><input type=\"radio\" name=\"sand\" id=\"ad\" style=\"margin-left: 100px;\" onclick=\"aFun()\">奥迪外观图</label>\r\n");
      out.write("</label> \r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<ul id=\"bullets\"></ul>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath() );
      out.write("/fore/carImg/swfobject.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("srlFun();\r\n");
      out.write("\r\n");
      out.write("function sFun(){\r\n");
      out.write("\tsrlFun();\r\n");
      out.write("}\r\n");
      out.write("function aFun(){\r\n");
      out.write("\tadFun();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 奥迪 */\r\n");
      out.write("function adFun(){\r\n");
      out.write("\t$(\"#flashcontent\").css(\"left\",\"345px\");\r\n");
      out.write("\t$(\"#adl\").css(\"color\",\"yellow\");\r\n");
      out.write("\t$(\"#mkl\").css(\"color\",\"black\");\r\n");
      out.write("\t\r\n");
      out.write("\tvar so = new SWFObject(\"");
      out.print(request.getContextPath() );
      out.write("/fore/carImage1/result6.swf\", \"result6.swf\", \"640px\", \"313px\", \"9.0.0\", \"#ffffff\");\r\n");
      out.write("\tso.addParam(\"quality\", \"high\");\r\n");
      out.write("    so.addParam(\"salign\", \"lt\");\r\n");
      out.write("    so.addParam(\"allowScriptAccess\", \"always\");\r\n");
      out.write("    so.addParam(\"allowFullScreen\", \"true\");\r\n");
      out.write("    so.addVariable(\"waitingPic\",\"wait.gif\");\r\n");
      out.write("    so.write(\"flashcontent\");\r\n");
      out.write("}\r\n");
      out.write("/* slr */\r\n");
      out.write("function srlFun(){\r\n");
      out.write("\t $(\"#flashcontent\").css(\"left\",\"315px\");\r\n");
      out.write("\t $(\"#adl\").css(\"color\",\"black\");\r\n");
      out.write("\t $(\"#mkl\").css(\"color\",\"yellow\");\r\n");
      out.write("\t\r\n");
      out.write("\t var so = new SWFObject(\"");
      out.print(request.getContextPath() );
      out.write("/fore/carImg/PWViewer.swf\", \"sotester\", \"700px\", \"390px\", \"9.0.0\", \"#FFFFFF\"); \r\n");
      out.write("\t so.addParam(\"allowNetworking\", \"all\"); \r\n");
      out.write("\t so.addParam(\"allowScriptAccess\", \"always\"); \r\n");
      out.write("\t so.addParam(\"allowFullScreen\", \"true\"); \r\n");
      out.write("\t so.addParam(\"scale\", \"noscale\"); \r\n");
      out.write("\t so.addVariable(\"configFileSize\", \"1.440\"); \r\n");
      out.write("\t so.addVariable(\"zipResSize\", \"0.000\"); \r\n");
      out.write("\t so.addVariable(\"sceneFilesSize\", \"553.258\"); \r\n");
      out.write("\t so.addVariable(\"base\", \"car/\"); \r\n");
      out.write("\t so.addVariable(\"lwImg\", \"resources/waiting.gif\"); \r\n");
      out.write("\t so.addVariable(\"lwBgColor\", \"255,255,255,255\"); \r\n");
      out.write("\t so.addVariable(\"lwBarBgColor\", \"255,45,91,141\"); \r\n");
      out.write("\t so.addVariable(\"lwBarColor\", \"255,130,170,215\"); \r\n");
      out.write("\t so.addVariable(\"lwBarBounds\", \"0,0,0,0\"); \r\n");
      out.write("\t so.addVariable(\"lwShowLoadingPercent\", \"false\"); \r\n");
      out.write("\t so.addVariable(\"iniFile\", \"config_car.bin\"); \r\n");
      out.write("\t so.addVariable(\"progressType\", \"0\"); \r\n");
      out.write("\t so.addVariable(\"swfFile\", \"\"); \r\n");
      out.write("\t so.addVariable(\"href\", location.href); \r\n");
      out.write("\t so.write(\"flashcontent\");\r\n");
      out.write("} \r\n");
      out.write("</script>         \r\n");
      out.write("<!-- 分享 -->\r\n");
      out.write("<script>\r\n");
      out.write("window._bd_share_config={\r\n");
      out.write("\t\t\"common\":{\"bdSnsKey\":{},\"bdText\":\"\",\"bdMini\":\"2\",\"bdMiniList\":false,\"bdPic\":\"\",\"bdStyle\":\"0\",\"bdSize\":\"16\"},\r\n");
      out.write("\t\t\"slide\":{\"type\":\"slide\",\"bdImg\":\"7\",\"bdPos\":\"right\",\"bdTop\":\"150\"},\r\n");
      out.write("\t\t\"image\":{\"viewList\":[\"qzone\",\"tsina\",\"tqq\",\"renren\",\"weixin\"],\r\n");
      out.write("\t\t\t\"viewText\":\"分享\",\"viewSize\":\"32\"},\r\n");
      out.write("\t\t\"selectShare\":{\"bdContainerClass\":null,\"bdSelectMiniList\":[\"qzone\",\"tsina\",\"tqq\",\"renren\",\"weixin\"]}};\r\n");
      out.write("\t\twith(document)0[(getElementsByTagName('head')[0]||body).appendChild(createElement('script')).src='http://bdimg.share.baidu.com/static/api/js/share.js?v=89860593.js?cdnversion='+~(-new Date()/36e5)];\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function zcFun(){\r\n");
      out.write("\t$(\"#in\").html(\"新用户注册\\n1.用户必须输入相应的值！\\n2.填入的手机号要接收短信验证码！\\n3.注册成功后即可登录！\");\r\n");
      out.write("}\r\n");
      out.write("function dlFun(){\r\n");
      out.write("\t$(\"#in\").html(\"用户登录\\n1.注册之后进行登录！\\n2.用户必须输入相应的值！\\n3.必须填入验证码！\");\r\n");
      out.write("}\r\n");
      out.write("function cxqcFun(){\r\n");
      out.write("\t$(\"#in\").html(\"查询汽车\\n\\n1.跳转到汽车主页！\\n\\n2.输入你想要查询的汽车的配置信息！\");\r\n");
      out.write("}\r\n");
      out.write("function grzyFun(){\r\n");
      out.write("\t$(\"#in\").html(\"个人主页\\n1.显示自己的信息！\\n2.修改密码！\\n3.充值余额！\\n4.兑换积分！\\n5.进行留言！\\n6.查看充值记录！\");\r\n");
      out.write("}\r\n");
      out.write("function yyqcFun(){\r\n");
      out.write("\t$(\"#in\").html(\"预约汽车\\n1.显示汽车和你的信息！\\n2.选择提、还车日期！\\n3.你必须选择提车地点！\\n4.地图中查询店铺！\");\r\n");
      out.write("}\r\n");
      out.write("function lxkfFun(){\r\n");
      out.write("\t$(\"#in\").html(\"联系客服：\\n1.和公司客服进行聊天，提出问题或改进意见！\\n2.你的好的意见会被采用的！\");\r\n");
      out.write("}\r\n");
      out.write("function qxFun(){\r\n");
      out.write("\t$(\"#in\").html(\"取消订单：\\n1.取消“已预约”状态的订单！\\n2.取消之后还可以看到！\\n3.你可以打印订单！\");\r\n");
      out.write("}\r\n");
      out.write("function zfFun(){\r\n");
      out.write("\t$(\"#in\").html(\"支付订单：\\n1.你可以选择网上在线支付方式！\\n2.支付完成之后记得按时到提车地点提车！\");\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function animationIn(i){\r\n");
      out.write("/* console.log(i,'i\\'m in') */\r\n");
      out.write("switch(i) {\r\n");
      out.write("    case 1:\r\n");
      out.write("        $('.page2 h2').fadeIn();\r\n");
      out.write("        break;\r\n");
      out.write("    default:\r\n");
      out.write("        ;\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write("function animationOut(i){\r\n");
      out.write("/* console.log(i,'i\\'m out') */\r\n");
      out.write("switch(i) {\r\n");
      out.write("    case 1:\r\n");
      out.write("        $('.page2 h2').fadeOut();\r\n");
      out.write("        break;\r\n");
      out.write("    default:\r\n");
      out.write("        ;\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<script src='");
      out.print(request.getContextPath() );
      out.write("/fore/js/jquery-1.7.2.min.js'></script>\r\n");
      out.write("<script src='");
      out.print(request.getContextPath() );
      out.write("/fore/css/frist/js/mousewheel.js'></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/fore/css/frist/js/jquery.touchSwipe.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/fore/css/frist/js/cubeTransition.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
